### ISSUE TITLE
swagger 

### ISSUE THREAD

**Issue by smilejakdu** [smilejakdu/showMeYourAbility#28]
spring boot 3.0 에서 swagger 를 추가 하려고 하는데 다양한 에러가 발생 ㅠ

**Comment by Duckxyh** [comment]
I want to know it. because once my Spring boot 3.0 integrate Swagger3,then open http://localhost:8080/swagger-ui/ and it will appear 404......

**Comment by smilejakdu** [comment]
hi :) i don't know i also want solution

**Comment by fimmsoul** [comment]
so 어려웡..... 스프링 부트

**Comment by Duckxyh** [comment]
May be We can exchange the dependicies? such as knief4j

**Comment by smilejakdu** [comment]
@Duckxyh  If you want to solve it, it may be better to change the spring boot version
I used a different version of spring boot in another project, and it didn't bother me too much.

**Comment by Duckxyh** [comment]
@smilejakdu ok,I get it. Thank you.
